<?xml version="1.0" encoding="utf-8"?><Database Name="MyFirstDB" Class="PeopleDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=MyFirstDB;Integrated Security=True" SettingsObjectName="VuejsClass.Data.Properties.Settings" SettingsPropertyName="MyFirstDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.People" Member="Persons">
    <Type Name="Person">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="People_People" Member="Person1" ThisKey="Id" OtherKey="Id" Type="Person" Cardinality="One" />
      <Association Name="People_People" Member="People1" ThisKey="Id" OtherKey="Id" Type="Person" IsForeignKey="true" />
    </Type>
  </Table>
</Database>